version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./dist:/usr/share/nginx/html:ro
            - ./nginx.debug.conf:/etc/nginx/conf.d/default.conf:ro
